name: PROBE 2 dropdown
description: adds a dropdown
body:
  - type: input
    id: a
    attributes:
      label: Anything
  - type: dropdown
    id: b
    attributes:
      label: Pick one
      options:
        - HiSilicon
        - Goke
    validations:
      required: true
